<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr_FR" sourcelanguage="fr_BE">
<context>
    <name>main</name>
    <message>
        <source>&amp;Fichier</source>
        <translation>&amp;Fichier</translation>
    </message>
    <message>
        <source>Quitter</source>
        <translation>Quitter</translation>
    </message>
    <message>
        <source>Titre</source>
        <translation>Titre</translation>
    </message>
    <message>
        <source>Auteur</source>
        <translation>Auteur</translation>
    </message>
    <message>
        <source>Éditeur</source>
        <translation>Éditeur</translation>
    </message>
    <message>
        <source>Publication</source>
        <translation>Publication</translation>
    </message>
    <message>
        <source>Prix</source>
        <translation>Prix</translation>
    </message>
    <message>
        <source>Détails</source>
        <translation>Détails</translation>
    </message>
    <message>
        <source>Genre</source>
        <translation>Genre</translation>
    </message>
    <message>
        <source>Année de publication</source>
        <translation>Année de publication</translation>
    </message>
    <message>
        <source>Résumé</source>
        <translation>Résumé</translation>
    </message>
    <message>
        <source>Nouveau</source>
        <translation>Nouveau</translation>
    </message>
    <message>
        <source>Sauvegarder</source>
        <translation>Sauvegarder</translation>
    </message>
    <message>
        <source>Supprimer</source>
        <translation>Supprimer</translation>
    </message>
</context>
</TS>
