# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Public\Espace_Eric6\biblioapp2_db\main_window_biblio.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowBiblio(object):
    def setupUi(self, MainWindowBiblio):
        MainWindowBiblio.setObjectName("MainWindowBiblio")
        MainWindowBiblio.resize(563, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindowBiblio)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeViewLivres = QtWidgets.QTreeView(self.centralwidget)
        self.treeViewLivres.setSortingEnabled(True)
        self.treeViewLivres.setObjectName("treeViewLivres")
        self.verticalLayout.addWidget(self.treeViewLivres)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditTitre = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditTitre.setObjectName("lineEditTitre")
        self.gridLayout.addWidget(self.lineEditTitre, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditAuteur = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditAuteur.setObjectName("lineEditAuteur")
        self.gridLayout.addWidget(self.lineEditAuteur, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBoxGenre = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxGenre.setObjectName("comboBoxGenre")
        self.horizontalLayout.addWidget(self.comboBoxGenre)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditEditeur = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditEditeur.setObjectName("lineEditEditeur")
        self.gridLayout.addWidget(self.lineEditEditeur, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dateEditAnnee = QtWidgets.QDateEdit(self.groupBox)
        self.dateEditAnnee.setSpecialValueText("")
        self.dateEditAnnee.setObjectName("dateEditAnnee")
        self.horizontalLayout_2.addWidget(self.dateEditAnnee)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.plainTextEditResume = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEditResume.setObjectName("plainTextEditResume")
        self.gridLayout.addWidget(self.plainTextEditResume, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.doubleSpinBoxPrix = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxPrix.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxPrix.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxPrix.setSpecialValueText("")
        self.doubleSpinBoxPrix.setMinimum(-0.01)
        self.doubleSpinBoxPrix.setMaximum(9999.99)
        self.doubleSpinBoxPrix.setProperty("value", -0.01)
        self.doubleSpinBoxPrix.setObjectName("doubleSpinBoxPrix")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxPrix)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButtonNouveau = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNouveau.setObjectName("pushButtonNouveau")
        self.horizontalLayout_4.addWidget(self.pushButtonNouveau)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pushButtonSauvegarder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSauvegarder.setObjectName("pushButtonSauvegarder")
        self.horizontalLayout_4.addWidget(self.pushButtonSauvegarder)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.horizontalLayout_4.addWidget(self.pushButtonSupprimer)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindowBiblio.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowBiblio)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 563, 21))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        MainWindowBiblio.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowBiblio)
        self.statusbar.setObjectName("statusbar")
        MainWindowBiblio.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(MainWindowBiblio)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionOuvrir = QtWidgets.QAction(MainWindowBiblio)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionEnregistrer = QtWidgets.QAction(MainWindowBiblio)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addAction(self.actionEnregistrer)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionQuitter)
        self.menuFichier.addSeparator()
        self.menubar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(MainWindowBiblio)
        QtCore.QMetaObject.connectSlotsByName(MainWindowBiblio)

    def retranslateUi(self, MainWindowBiblio):
        _translate = QtCore.QCoreApplication.translate
        MainWindowBiblio.setWindowTitle(_translate("MainWindowBiblio", "BiblioApp"))
        self.groupBox.setTitle(_translate("MainWindowBiblio", "Détails"))
        self.label.setText(_translate("MainWindowBiblio", "Titre"))
        self.label_2.setText(_translate("MainWindowBiblio", "Auteur(s)"))
        self.label_3.setText(_translate("MainWindowBiblio", "Genre"))
        self.label_4.setText(_translate("MainWindowBiblio", "Éditeur"))
        self.label_5.setText(_translate("MainWindowBiblio", "Année de parution"))
        self.dateEditAnnee.setDisplayFormat(_translate("MainWindowBiblio", "yyyy"))
        self.label_6.setText(_translate("MainWindowBiblio", "Résumé"))
        self.label_7.setText(_translate("MainWindowBiblio", "Prix"))
        self.doubleSpinBoxPrix.setSuffix(_translate("MainWindowBiblio", " €"))
        self.pushButtonNouveau.setText(_translate("MainWindowBiblio", "Nouveau"))
        self.pushButtonSauvegarder.setText(_translate("MainWindowBiblio", "Sauvegarder"))
        self.pushButtonSupprimer.setText(_translate("MainWindowBiblio", "Supprimer"))
        self.menuFichier.setTitle(_translate("MainWindowBiblio", "&Fichier"))
        self.actionQuitter.setText(_translate("MainWindowBiblio", "&Quitter"))
        self.actionOuvrir.setText(_translate("MainWindowBiblio", "&Ouvrir..."))
        self.actionOuvrir.setShortcut(_translate("MainWindowBiblio", "Ctrl+O"))
        self.actionEnregistrer.setText(_translate("MainWindowBiblio", "&Enregistrer"))
        self.actionEnregistrer.setShortcut(_translate("MainWindowBiblio", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowBiblio = QtWidgets.QMainWindow()
    ui = Ui_MainWindowBiblio()
    ui.setupUi(MainWindowBiblio)
    MainWindowBiblio.show()
    sys.exit(app.exec_())

